### ISSUE TITLE
Joint transforms not published anymore after clock reset

### ISSUE THREAD

**Issue by tlind** [ros/robot_state_publisher#17]
Once the ROS clock gets reset to an earlier time (e.g. while playing a bag file using `rosbag play --loop`), joint transforms belonging to non-fixed joints are never published again. Fixed joints, however, still work fine.

**Comment by tlind** [comment]
I've added a fix in pull request #18.

**Comment by jackieokay** [comment]
I'm closing it because a fix has been merged. Let me know if it needs to be reopened.

**Comment by guihomework** [comment]
I fell in this issue again, either because of no luck or because of bad data on my side, not completely sure.

here is the thing : It happened that the loop reset cleared the last_time_published due to clock reset/loop but the joint state message header being processed was still the last one of the bag file before reset/loop.
then the wrong time (in the future) is stored and never gets updated anymore

```
joint_state stamp = 1501506017.585520   
[INFO sim time =  1501506017.615704348] last_published + publish_internal =1501506017.555149
[WARN  sim time = 1501505983.840299137 ] Moved backwards in time  (...)
```
=> last_published_time_ cleared
```
last_published_time_ all 0.000000
joint_state stamp = 1501506017.625759 
last_published + publish_internal = 0.020000
```
=> above one sees the joint_state stamp is in the future. Because ```last_published + publish_internal is very small ``` it will publis  and then  ```last_published_time = 1501506017.625759```
=> this is wrong. A bad time is stored.

In later loop the last_published time being in the future, nothing gets published anymore
```
joint_state stamp = 1501505987.123558 
last_published + publish_internal = 1501505987.183780
```
=> not publishing
at this line https://github.com/ros/robot_state_publisher/blob/kinetic-devel/src/joint_state_listener.cpp#L116
``` t = 1501506017.625759 ```  => is still stuck at the last publication before the loop
and the test makes temporarily change value to current joint_state stamp, 
```
last_published = 1501505987.204575
```
which is not far enough in the future (due to rate) to be published and so no last_published_time updated.


I could circumvent this by using _ignore_timestamp_ parameter.

I wonder if such a protection could be accepted in a PR. It basically accepts to publish only if the time in the joint_state is in the past relative to "now".

at https://github.com/ros/robot_state_publisher/blob/kinetic-devel/src/joint_state_listener.cpp#L123
```
-  if (ignore_timestamp_ || state->header.stamp >= last_published + publish_interval_) 
+  if (ignore_timestamp_ || (state->header.stamp >= last_published + publish_interval_ && state->header.stamp <= now) ) 
```
worked for me at least.
