### ISSUE TITLE
Make `ros2` the default branch

### ISSUE THREAD

**Issue by sloretz** [ros/robot_state_publisher#178]
@clalancette thoughts on making the ROS Rolling branch `ros2` the default? New PRs should happen against rolling anyways.

**Comment by clalancette** [comment]
I'm conflicted.  On the one hand, changing the default from `noetic-devel` -> `ros2` isn't just moving to the latest; it is qualitatively different.  On the other hand, most new development will likely be targeting ROS 2, so making everyone change the branch for PRs is a bit of extra clicking.

In the interest of "do no harm", I've generally opted to leave repositories that are shared between ROS 1 and ROS 2 on the ROS 1 branch until end-of-life.  But if you feel strongly otherwise, I won't argue against it.

**Comment by sloretz** [comment]
> In the interest of "do no harm", I've generally opted to leave repositories that are shared between ROS 1 and ROS 2 on the ROS 1 branch until end-of-life

Is the concern about a user having a workflow of `git clone ...` without specifying a branch and them getting the wrong version of the software? I think the ROS 1 ecosystem is well equipped to handle that with `ros/rosdistro` and `rosinstall_generator`. I can't recall Melodic hearing about users being broken anytime a default branch became `noetic-devel`.

I brought it up because #177 targeted the `galactic` branch instead of the `ros2` branch. I think making the latest development branch the default helps remove some of the friction from contributing.

**Comment by clalancette** [comment]
> Is the concern about a user having a workflow of `git clone ...` without specifying a branch and them getting the wrong version of the software? I think the ROS 1 ecosystem is well equipped to handle that with `ros/rosdistro` and `rosinstall_generator`. I can't recall Melodic hearing about users being broken anytime a default branch became `noetic-devel`.

Since `rosinstall_generator` works in ROS 2 as well, I had to think about why things are different between ROS 1 and ROS 2.  

In ROS 1, we generally only change the branch name when we introduce incompatible changes between branches, so doing a `rosinstall_generator` against Melodic will usually get you the correct branch (either you'll get the latest branch, which also works for Melodic, or you'll get the `melodic-devel` branch, which is what you want to target).

In ROS 2, Rolling changes that equation.  Since we now typically have a separate branch for Rolling, doing a `rosinstall_generator` against Galactic will usually get you the *incorrect* branch.  That's because we want everything to go into Rolling and flow down from there.

Thinking about it that way, you've convinced me.  Feel free to change the default branch.

**Comment by sloretz** [comment]
>  Feel free to change the default branch.

Done!
